version: '3'

tasks:
  build:
    deps: [regen]
    cmds:
      - go build -o ./dist/certgen{{.EXE}} ./certgen/cmd
      - go build -o ./dist/tokengen{{.EXE}} ./tokengen/cmd
      - go build -o ./dist/server{{.EXE}} ./greeter_server
      - go build -o ./dist/client{{.EXE}} ./greeter_client
    vars:
      EXE:
        sh: go env GOEXE

  greet:
    cmds:
      - ./dist/client

  newtoken:
    cmds:
      - ./dist/tokengen

  expiredtoken:
    cmds:
      - ./dist/tokengen --expired

  cert:
    cmds:
      - ./dist/certgen

  serve:
    cmds:
      - ./dist/server

  regen:
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
          pb/helloworld.proto
